export const dataItems = [
    {
      scanName: 'Itsecgames active scanning from VM',
      targetUrl: 'http://www.itsecgames.com/',
      scanEngine: 'Engine - Jan 10',
      status: 'Completed',
      rank: 'B',
      totalVulnerabilities: 212,
      severity: { green: 5, orange: 78, red: 99, gray: 30 },
    },
    {
      scanName: 'Dotika scanning from VM',
      targetUrl: 'https://dotika.io',
      scanEngine: 'tanishq doing testing (wow)',
      status: 'Completed',
      rank: 'B',
      totalVulnerabilities: 212,
      severity: { green: 5, orange: 78, red: 99, gray: 30 },
    },
    {
      scanName: 'Security Scan #3',
      targetUrl: 'http://example3.com',
      scanEngine: 'Engine - Feb 15',
      status: 'Completed',
      rank: 'A',
      totalVulnerabilities: 150,
      severity: { green: 10, orange: 50, red: 60, gray: 30 },
    },
    {
      scanName: 'Security Scan #4',
      targetUrl: 'http://example4.com',
      scanEngine: 'Engine - Mar 20',
      status: 'In Progress',
      rank: 'C',
      totalVulnerabilities: 300,
      severity: { green: 15, orange: 100, red: 150, gray: 35 },
    },
    {
      scanName: 'Security Scan #5',
      targetUrl: 'http://example5.com',
      scanEngine: 'Engine - Apr 25',
      status: 'Completed',
      rank: 'A',
      totalVulnerabilities: 180,
      severity: { green: 20, orange: 60, red: 80, gray: 20 },
    },
    {
      scanName: 'Security Scan #6',
      targetUrl: 'http://example6.com',
      scanEngine: 'Engine - May 30',
      status: 'Pending',
      rank: 'B',
      totalVulnerabilities: 220,
      severity: { green: 25, orange: 80, red: 90, gray: 25 },
    },
    {
      scanName: 'Security Scan #7',
      targetUrl: 'http://example7.com',
      scanEngine: 'Engine - Jun 10',
      status: 'Completed',
      rank: 'B',
      totalVulnerabilities: 190,
      severity: { green: 18, orange: 70, red: 85, gray: 17 },
    },
    {
      scanName: 'Security Scan #8',
      targetUrl: 'http://example8.com',
      scanEngine: 'Engine - Jul 15',
      status: 'In Progress',
      rank: 'C',
      totalVulnerabilities: 250,
      severity: { green: 12, orange: 90, red: 120, gray: 28 },
    },
    {
      scanName: 'Security Scan #9',
      targetUrl: 'http://example9.com',
      scanEngine: 'Engine - Aug 20',
      status: 'Completed',
      rank: 'A',
      totalVulnerabilities: 160,
      severity: { green: 22, orange: 55, red: 65, gray: 18 },
    },
    {
      scanName: 'Security Scan #10',
      targetUrl: 'http://example10.com',
      scanEngine: 'Engine - Sep 25',
      status: 'Completed',
      rank: 'B',
      totalVulnerabilities: 210,
      severity: { green: 20, orange: 75, red: 95, gray: 20 },
    },
    {
      scanName: 'Security Scan #11',
      targetUrl: 'http://example11.com',
      scanEngine: 'Engine - Oct 30',
      status: 'Pending',
      rank: 'C',
      totalVulnerabilities: 230,
      severity: { green: 15, orange: 85, red: 110, gray: 20 },
    },
    {
      scanName: 'Security Scan #12',
      targetUrl: 'http://example12.com',
      scanEngine: 'Engine - Nov 5',
      status: 'Completed',
      rank: 'A',
      totalVulnerabilities: 175,
      severity: { green: 25, orange: 60, red: 70, gray: 20 },
    },
  ];
  